// claude-in-dsh build — generates lib/ from src/.
//
// The engine was developed and tested as a DYNAMIC Cordis package (via
// dsh-cordis-mcp), whose two halves are plain function bodies evaluated with a
// few ambient globals. This build wraps those exact bodies in the formal bundle
// containers instead of rewriting them, so what ships is what was tested:
//
//   host   src/host.dynamic.js    globals: harness (RPC table), console
//          → lib/index.js         ES module { apply, inject }; the `harness`
//                                 table is served over one same-origin route,
//                                 POST /claude-in-dsh/rpc (loopback-guarded).
//   client src/client.dynamic.js  globals: React, console, styles, host, harness
//          → lib/client.js        window.__ModuleLoader__ bundle; `host.call`
//                                 becomes a fetch to that route, `styles.insert`
//                                 a <style> tag tagged data-plugin.
//   broker src/broker.mjs         → lib/broker.mjs (reference copy; the host
//                                 embeds its own source and writes /tmp/ccmode).

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8')
const write = (rel, text) => {
  fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true })
  fs.writeFileSync(path.join(root, rel), text)
  console.log('built', rel, `(${Buffer.byteLength(text)} bytes)`)
}

const hostBody = read('src/host.dynamic.js')
const clientBody = read('src/client.dynamic.js')

// ---------------------------------------------------------------------------

const indexJs = `// claude-in-dsh — host half (generated by scripts/build.mjs, do not edit).
//
// Hands one dsh conversation to the local Claude Code CLI while every part of
// it lands in dsh's own durable session vocabulary. The engine body below is
// byte-identical to the dynamic package it was developed and tested as; this
// file only supplies the two things the dynamic sandbox provided ambiently:
// the \`harness\` RPC table (served over one loopback-guarded route) and module
// packaging.

const inject = ['webServer', 'subprocess', 'timer']

/** Loopback + same-origin only — the guard dsh's own status routes use. */
function isLoopbackHostname(hostname) {
  return hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '::1' || hostname === '[::1]'
}

function isTrusted(req) {
  const host = req.headers.host
  if (!host) return false
  if (!isLoopbackHostname(host.split(':')[0])) return false
  if (req.headers['sec-fetch-site'] === 'cross-site') return false
  const origin = req.headers.origin
  if (origin === undefined) return true
  try { return new URL(origin).host === host } catch (error) { return false }
}

function writeJson(res, status, value) {
  const body = JSON.stringify(value)
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': Buffer.byteLength(body),
  })
  res.end(body)
}

function readRequestBody(req) {
  return new Promise((resolve, reject) => {
    let text = ''
    req.on('data', (chunk) => { text += String(chunk) })
    req.on('end', () => resolve(text))
    req.on('error', reject)
  })
}

// ---------------------------------------------------------------------------
// The tested engine, verbatim. Its own \`inject\` (['timer']) is subsumed by
// this module's; its \`apply\` is what this module's apply delegates to.

function engineHalf(harness) {
${hostBody}
}

function apply(ctx) {
  const rpc = new Map()
  const harness = {
    handle: (name, fn) => {
      rpc.set(name, fn)
      return () => { rpc.delete(name) }
    },
  }

  ctx.effect(() => ctx.webServer.register({
    kind: 'exact',
    path: '/claude-in-dsh/rpc',
    handler: async (req, res) => {
      if (!isTrusted(req)) return writeJson(res, 403, { ok: false, error: 'forbidden' })
      let payload = null
      try { payload = JSON.parse(await readRequestBody(req)) } catch (error) { payload = null }
      const method = payload === null ? '' : String(payload.method || '')
      const handler = rpc.get(method)
      if (handler === undefined) return writeJson(res, 404, { ok: false, error: 'unknown method: ' + method })
      try {
        const value = await handler(payload.args === undefined ? {} : payload.args)
        writeJson(res, 200, { ok: true, value: value === undefined ? null : value })
      } catch (error) {
        writeJson(res, 500, { ok: false, error: error && error.message ? String(error.message) : String(error) })
      }
    },
  }), 'claude-in-dsh: rpc route')

  return engineHalf(harness).apply(ctx)
}

export { apply, inject }
`

// ---------------------------------------------------------------------------

const clientJs = `// claude-in-dsh — client half (generated by scripts/build.mjs, do not edit).
window.__ModuleLoader__.load({
  id: 'claude-in-dsh',
  factory: function (require) {
    var module = { exports: {} }
    var exports = module.exports
    var React = require('react')
    var console = window.console

    var styles = {
      insert: function (css) {
        var tag = document.createElement('style')
        tag.setAttribute('data-plugin', 'claude-in-dsh')
        tag.textContent = css
        document.head.appendChild(tag)
      },
    }

    // The dynamic sandbox's host bridge, over the bundle's own loopback route.
    var host = {
      call: function (method, args) {
        return fetch('/claude-in-dsh/rpc', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ method: method, args: args === undefined ? {} : args }),
        }).then(function (response) { return response.json() }).then(function (answer) {
          if (answer === null || answer.ok !== true) {
            throw new Error(answer && answer.error ? String(answer.error) : 'claude-in-dsh: rpc failed')
          }
          return answer.value
        })
      },
    }

    var harness = {}

    var half = (function () {
${clientBody}
    })()

    exports.apply = half.apply
    // The services the body reaches via ctx.get / ctx mixins. Matches what
    // dsh's own client packages declare (ui-permission-presets injects the
    // same set), so a missing name fails at load, not silently at runtime.
    exports.inject = ['slots', 'commandUi', 'sessions', 'timer', 'remote']
    return module.exports
  },
})
`

write('lib/index.js', indexJs)
write('lib/client.js', clientJs)
fs.copyFileSync(path.join(root, 'src/broker.mjs'), path.join(root, 'lib/broker.mjs'))
console.log('built lib/broker.mjs (copy of src/broker.mjs)')
